# Generated by Django 5.1.2 on 2025-01-15 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='contact_hours',
        ),
        migrations.RemoveField(
            model_name='course',
            name='writer',
        ),
        migrations.AlterField(
            model_name='course',
            name='approved_by',
            field=models.CharField(default='Not Approved', max_length=100),
        ),
    ]
